create table public.estudiantes (
  id bigint generated by default as identity not null,
  nombre text null,
  apellido text null,
  correo text null,
  carrera text null,
  created_at timestamp with time zone not null default now(),
  constraint estudiantes_pkey primary key (id)
) TABLESPACE pg_default;
